INSERT INTO public."payment_activity_data" (payee_name, part_postcode, town, county_council, parliamentary_constituency, scheme, scheme_detail, activity_level, financial_year, amount) VALUES ('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 3593),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 1444),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 2553),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 3976),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 4302),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 1333),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 2430),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 1380),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 3531),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 4592),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 1390),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 1772),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 3380),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '23/24', 2400),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Farming Equipment and Technology Fund', 'Forestry', '', '23/24', 3632),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '23/24', 4521),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '23/24', 1250),
('Maria Wilderman', 'CF32', 'Ogmore Valley', 'None', 'Ogmore', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 3911),
('Vickie Dicki', 'BN12', 'Worthing, unparished area', 'West Sussex', 'Worthing West', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 4709),
('Vickie Dicki', 'BN12', 'Worthing, unparished area', 'West Sussex', 'Worthing West', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Vickie Dicki', 'BN12', 'Worthing, unparished area', 'West Sussex', 'Worthing West', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 2445),
('Vickie Dicki', 'BN12', 'Worthing, unparished area', 'West Sussex', 'Worthing West', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 4470),
('Moses Bruen', 'DA11', 'Gravesham, unparished area', 'Kent', 'Gravesham', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 4669),
('Moses Bruen', 'DA11', 'Gravesham, unparished area', 'Kent', 'Gravesham', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 3874),
('Moses Bruen', 'DA11', 'Gravesham, unparished area', 'Kent', 'Gravesham', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 1571),
('Moses Bruen', 'DA11', 'Gravesham, unparished area', 'Kent', 'Gravesham', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 3289),
('Sandie Kub', 'EX19', 'Monkokehampton', 'Devon', 'Central Devon', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 2370),
('Sandie Kub', 'EX19', 'Monkokehampton', 'Devon', 'Central Devon', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 1385),
('Sandie Kub', 'EX19', 'Monkokehampton', 'Devon', 'Central Devon', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '23/24', 1466),
('Buddy Klocko', 'KY7', 'None', 'None', 'Glenrothes', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 2017),
('Buddy Klocko', 'KY7', 'None', 'None', 'Glenrothes', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 3808),
('Buddy Klocko', 'KY7', 'None', 'None', 'Glenrothes', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 4204),
('Buddy Klocko', 'KY7', 'None', 'None', 'Glenrothes', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 4908),
('Buddy Klocko', 'KY7', 'None', 'None', 'Glenrothes', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 2613),
('Buddy Klocko', 'KY7', 'None', 'None', 'Glenrothes', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 4626),
('Marquitta Kautzer', 'GL53', 'Leckhampton with Warden Hill', 'Gloucestershire', 'Cheltenham', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 2338),
('Marquitta Kautzer', 'GL53', 'Leckhampton with Warden Hill', 'Gloucestershire', 'Cheltenham', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 4133),
('Marquitta Kautzer', 'GL53', 'Leckhampton with Warden Hill', 'Gloucestershire', 'Cheltenham', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 3702),
('Marquitta Kautzer', 'GL53', 'Leckhampton with Warden Hill', 'Gloucestershire', 'Cheltenham', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 3958),
('Steven Huel', 'BT35', 'None', 'None', 'Newry and Armagh', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 1513),
('Steven Huel', 'BT35', 'None', 'None', 'Newry and Armagh', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 2957),
('Steven Huel', 'BT35', 'None', 'None', 'Newry and Armagh', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 4135),
('Steven Huel', 'BT35', 'None', 'None', 'Newry and Armagh', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 1508),
('Steven Huel', 'BT35', 'None', 'None', 'Newry and Armagh', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 2899),
('Rueben Carter', 'CF64', 'Barry', 'None', 'Vale of Glamorgan', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 2795),
('Rueben Carter', 'CF64', 'Barry', 'None', 'Vale of Glamorgan', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 3942),
('Rueben Carter', 'CF64', 'Barry', 'None', 'Vale of Glamorgan', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '23/24', 1681),
('Rae Rohan', 'BH24', 'Ringwood', 'Hampshire', 'New Forest West', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 2391),
('Rae Rohan', 'BH24', 'Ringwood', 'Hampshire', 'New Forest West', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 4208),
('Rae Rohan', 'BH24', 'Ringwood', 'Hampshire', 'New Forest West', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 2281),
('Rae Rohan', 'BH24', 'Ringwood', 'Hampshire', 'New Forest West', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 3751),
('Rosio Hills', 'CH47', 'Wirral, unparished area', 'None', 'Wirral West', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 4187),
('Rosio Hills', 'CH47', 'Wirral, unparished area', 'None', 'Wirral West', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 4521),
('Rosio Hills', 'CH47', 'Wirral, unparished area', 'None', 'Wirral West', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 1877),
('Rosio Hills', 'CH47', 'Wirral, unparished area', 'None', 'Wirral West', 'Farming Equipment and Technology Fund', 'Horticulture', '', '22/23', 2412),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 4018),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 1861),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 4641),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 1557),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '23/24', 2665),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '23/24', 3099),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '24/25', 4740),
('Sarita Dicki', 'W5', 'Ealing, unparished area', 'None', 'Ealing Central and Acton', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '24/25', 2825),
('Hunter Schulist', 'EH11', 'None', 'None', 'Edinburgh South West', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 4429),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 2058),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 3642),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 4352),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 3732),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 4300),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 4175),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 2879),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 2829),
('Fredrick Auer', 'TS24', 'Hartlepool, unparished area', 'None', 'Hartlepool', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 1917),
('Janay McDermott', 'SK5', 'Stockport, unparished area', 'None', 'Denton and Reddish', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 1284),
('Janay McDermott', 'SK5', 'Stockport, unparished area', 'None', 'Denton and Reddish', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 4293),
('Janay McDermott', 'SK5', 'Stockport, unparished area', 'None', 'Denton and Reddish', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 1658),
('Janay McDermott', 'SK5', 'Stockport, unparished area', 'None', 'Denton and Reddish', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 2300),
('Cris Blick', 'NE2', 'Newcastle upon Tyne, unparished area', 'None', 'Newcastle upon Tyne East', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 1600),
('Cris Blick', 'NE2', 'Newcastle upon Tyne, unparished area', 'None', 'Newcastle upon Tyne East', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 3928),
('Cris Blick', 'NE2', 'Newcastle upon Tyne, unparished area', 'None', 'Newcastle upon Tyne East', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 3264),
('Cris Blick', 'NE2', 'Newcastle upon Tyne, unparished area', 'None', 'Newcastle upon Tyne East', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 2010),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 1259),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 4400),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 2205),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 3863),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 2910),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 1913),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Farming Equipment and Technology Fund', 'Horticulture', '', '23/24', 3065),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 2275),
('Ryan Spencer', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 3846),
('Sheldon Kiehn', 'CA7', 'Plumbland', 'Cumbria', 'Workington', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 3258),
('Sheldon Kiehn', 'CA7', 'Plumbland', 'Cumbria', 'Workington', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 1294),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 1482),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 1646),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 2197),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 2153),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 3284),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 3751),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 4843),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 2328),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Ty Hickle', 'YO25', 'Driffield', 'None', 'East Yorkshire', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 4016),
('Barton Farrell', 'YO21', 'Whitby', 'North Yorkshire', 'Scarborough and Whitby', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Barton Farrell', 'YO21', 'Whitby', 'North Yorkshire', 'Scarborough and Whitby', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 3494),
('Barton Farrell', 'YO21', 'Whitby', 'North Yorkshire', 'Scarborough and Whitby', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 4757),
('Barton Farrell', 'YO21', 'Whitby', 'North Yorkshire', 'Scarborough and Whitby', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 1849),
('Barton Farrell', 'YO21', 'Whitby', 'North Yorkshire', 'Scarborough and Whitby', 'Farming Equipment and Technology Fund', 'Forestry', '', '23/24', 2299),
('Barton Farrell', 'YO21', 'Whitby', 'North Yorkshire', 'Scarborough and Whitby', 'Farming Equipment and Technology Fund', 'Resource Management', '', '23/24', 4649),
('Kimberli Dach', 'ST13', 'Leek', 'Staffordshire', 'Staffordshire Moorlands', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 4106),
('Kimberli Dach', 'ST13', 'Leek', 'Staffordshire', 'Staffordshire Moorlands', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 4559),
('Kimberli Dach', 'ST13', 'Leek', 'Staffordshire', 'Staffordshire Moorlands', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 1772),
('Kimberli Dach', 'ST13', 'Leek', 'Staffordshire', 'Staffordshire Moorlands', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2551),
('Timmy Deckow', 'BT47', 'None', 'None', 'Foyle', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 2999),
('Timmy Deckow', 'BT47', 'None', 'None', 'Foyle', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Timmy Deckow', 'BT47', 'None', 'None', 'Foyle', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 4470),
('Jennell Pollich', 'OX14', 'Abingdon on Thames', 'Oxfordshire', 'Oxford West and Abingdon', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 3228),
('Jennell Pollich', 'OX14', 'Abingdon on Thames', 'Oxfordshire', 'Oxford West and Abingdon', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 4567),
('Jennell Pollich', 'OX14', 'Abingdon on Thames', 'Oxfordshire', 'Oxford West and Abingdon', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 3856),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 4827),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 3762),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 2433),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 2924),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 1792),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 1669),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 3729),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 3226),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 4615),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 4988),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '23/24', 1250),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 2986),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 2115),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 2809),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 4564),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '24/25', 4904),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '24/25', 2578),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '24/25', 2968),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '24/25', 1672),
('Gwyneth Waters', 'SG5', 'North Hertfordshire, unparished area', 'Hertfordshire', 'Hitchin and Harpenden', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '24/25', 3517),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 1903),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 3216),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 2067),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 1471),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 3801),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 2173),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '23/24', 3034),
('Granville Collier', 'BH1', 'Bournemouth, Christchurch and Poole, unparished area', 'None', 'Bournemouth West', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 2048),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 3438),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 4699),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 2463),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 4880),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2368),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 4855),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 3672),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 4361),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 4866),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Farming Equipment and Technology Fund', 'Forestry', '', '23/24', 1907),
('Joella Cummings', 'SY3', 'Shrewsbury', 'None', 'Shrewsbury and Atcham', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 1313),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 1586),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 2997),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 2691),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 4689),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 2773),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 2593),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 3951),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 4114),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 3975),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 3902),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Farming Equipment and Technology Fund', 'Horticulture', '', '22/23', 3791),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 3207),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '23/24', 2525),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '23/24', 1458),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Farming Equipment and Technology Fund', 'Forestry', '', '23/24', 4754),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '23/24', 1987),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 4054),
('Bertram Langworth', 'EX1', 'Exeter, unparished area', 'Devon', 'Exeter', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 4950),
('Rosemarie Gutmann', 'BA21', 'Yeovil', 'Somerset', 'Yeovil', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 1945),
('Rosemarie Gutmann', 'BA21', 'Yeovil', 'Somerset', 'Yeovil', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 4481),
('Rosemarie Gutmann', 'BA21', 'Yeovil', 'Somerset', 'Yeovil', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 2154),
('Rosemarie Gutmann', 'BA21', 'Yeovil', 'Somerset', 'Yeovil', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 3607),
('Rosemarie Gutmann', 'BA21', 'Yeovil', 'Somerset', 'Yeovil', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 3813),
('Rosemarie Gutmann', 'BA21', 'Yeovil', 'Somerset', 'Yeovil', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 2690),
('Daniel Muller', 'BN2', 'Brighton and Hove, unparished area', 'None', 'Brighton, Kemptown', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 2368),
('Daniel Muller', 'BN2', 'Brighton and Hove, unparished area', 'None', 'Brighton, Kemptown', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 4922),
('Daniel Muller', 'BN2', 'Brighton and Hove, unparished area', 'None', 'Brighton, Kemptown', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 2705),
('Rayford Ratke', 'SE15', 'Southwark, unparished area', 'None', 'Camberwell and Peckham', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 3283),
('Rayford Ratke', 'SE15', 'Southwark, unparished area', 'None', 'Camberwell and Peckham', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 4341),
('Rayford Ratke', 'SE15', 'Southwark, unparished area', 'None', 'Camberwell and Peckham', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 1633),
('Rayford Ratke', 'SE15', 'Southwark, unparished area', 'None', 'Camberwell and Peckham', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 1551),
('Deirdre Funk', 'LL53', 'Nefyn', 'None', 'Dwyfor Meirionnydd', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 1563),
('Fredrick Crist', 'NP13', 'Abertillery', 'None', 'Blaenau Gwent', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 2751),
('Fredrick Crist', 'NP13', 'Abertillery', 'None', 'Blaenau Gwent', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 4766),
('Fredrick Crist', 'NP13', 'Abertillery', 'None', 'Blaenau Gwent', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '23/24', 2969),
('Kirby Jast', 'PH7', 'None', 'None', 'Ochil and South Perthshire', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 1970),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 4389),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 3090),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 4971),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 4933),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 1903),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 4182),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 2375),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 2420),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 2315),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 3851),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '23/24', 2288),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'Forestry', '', '23/24', 1529),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 4114),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 3435),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '23/24', 1250),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'Forestry', '', '24/25', 2905),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '24/25', 4259),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '24/25', 1770),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '24/25', 1517),
('Elodia Carter', 'S6', 'Bradfield', 'None', 'Sheffield, Hallam', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '24/25', 4335),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 1579),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 2021),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 3271),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 2114),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 4013),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 3699),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 1612),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2199),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 4156),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '23/24', 1632),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '23/24', 4054),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 4692),
('Burton Wiegand', 'EN6', 'Hertsmere, unparished area', 'Hertfordshire', 'Hertsmere', 'Farming Equipment and Technology Fund', 'Forestry', '', '23/24', 2943),
('Lenard Prohaska', 'DD2', 'None', 'None', 'Dundee West', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 2320),
('Lenard Prohaska', 'DD2', 'None', 'None', 'Dundee West', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 4859),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 3183),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 4914),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 4405),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 2354),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 2579),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 4140),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 1986),
('Loren Sporer', 'KA3', 'None', 'None', 'Kilmarnock and Loudoun', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 2725),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 2456),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 4005),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 2712),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 1269),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 3586),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 3310),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 4315),
('Marlin Kozey', 'GL10', 'Stonehouse', 'Gloucestershire', 'Stroud', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 2655),
('Lindy Upton', 'OX2', 'Oxford, unparished area', 'Oxfordshire', 'Oxford East', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 2906),
('Lindy Upton', 'OX2', 'Oxford, unparished area', 'Oxfordshire', 'Oxford East', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 1475),
('Lindy Upton', 'OX2', 'Oxford, unparished area', 'Oxfordshire', 'Oxford East', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 3947),
('Lindy Upton', 'OX2', 'Oxford, unparished area', 'Oxfordshire', 'Oxford East', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 4609),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 1675),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 4008),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 4758),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 3027),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 3659),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 1664),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 4880),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 1570),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Horticulture', '', '22/23', 3715),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 4376),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Resource Management', '', '23/24', 2089),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '23/24', 3986),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '23/24', 4819),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 3929),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '24/25', 3937),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Forestry', '', '24/25', 2025),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'General', '', '24/25', 2294),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '24/25', 2675),
('Maxine Goyette', 'WS1', 'Walsall, unparished area', 'None', 'Walsall South', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '24/25', 4353),
('Lanny Gibson', 'SY24', 'Tirymynach', 'None', 'Ceredigion', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 3992),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 2249),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 3050),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 1446),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 2232),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 3897),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 2062),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 3195),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 4239),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 1325),
('Fidelia Romaguera', 'PR2', 'Preston, unparished area', 'Lancashire', 'Preston', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 4155),
('Lakeesha Heller', 'NG13', 'Bingham', 'Nottinghamshire', 'Newark', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 2251),
('Lakeesha Heller', 'NG13', 'Bingham', 'Nottinghamshire', 'Newark', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 2192),
('Lakeesha Heller', 'NG13', 'Bingham', 'Nottinghamshire', 'Newark', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 2776),
('Lakeesha Heller', 'NG13', 'Bingham', 'Nottinghamshire', 'Newark', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 1908),
('Lakeesha Heller', 'NG13', 'Bingham', 'Nottinghamshire', 'Newark', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 2911),
('Domingo White', 'BT82', 'None', 'None', 'West Tyrone', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 2172),
('Domingo White', 'BT82', 'None', 'None', 'West Tyrone', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 3925),
('Domingo White', 'BT82', 'None', 'None', 'West Tyrone', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 2571),
('Domingo White', 'BT82', 'None', 'None', 'West Tyrone', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 2679),
('Domingo White', 'BT82', 'None', 'None', 'West Tyrone', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Domingo White', 'BT82', 'None', 'None', 'West Tyrone', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 3752),
('Rolando Ullrich', 'EX15', 'Uffculme', 'Devon', 'Tiverton and Honiton', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 3325),
('Rolando Ullrich', 'EX15', 'Uffculme', 'Devon', 'Tiverton and Honiton', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 4489),
('Rolando Ullrich', 'EX15', 'Uffculme', 'Devon', 'Tiverton and Honiton', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 3883),
('Rolando Ullrich', 'EX15', 'Uffculme', 'Devon', 'Tiverton and Honiton', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 1771),
('Rolando Ullrich', 'EX15', 'Uffculme', 'Devon', 'Tiverton and Honiton', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 3466),
('Rolando Ullrich', 'EX15', 'Uffculme', 'Devon', 'Tiverton and Honiton', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 2470),
('Norberto Feeney', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 3390),
('Norberto Feeney', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 3134),
('Norberto Feeney', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Farming Equipment and Technology Fund', 'Horticulture', '', '22/23', 1886),
('Norberto Feeney', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 3574),
('Norberto Feeney', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 4491),
('Norberto Feeney', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 1650),
('Maria Breitenberg', 'SA14', 'Llangennech', 'None', 'Llanelli', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 2009),
('Maria Breitenberg', 'SA14', 'Llangennech', 'None', 'Llanelli', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Maria Breitenberg', 'SA14', 'Llangennech', 'None', 'Llanelli', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 3419),
('Maria Breitenberg', 'SA14', 'Llangennech', 'None', 'Llanelli', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 4860),
('Maria Breitenberg', 'SA14', 'Llangennech', 'None', 'Llanelli', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 1268),
('Kyung Torphy', 'CO15', 'Tendring, unparished area', 'Essex', 'Clacton', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 4003),
('Kyung Torphy', 'CO15', 'Tendring, unparished area', 'Essex', 'Clacton', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 4274),
('Kyung Torphy', 'CO15', 'Tendring, unparished area', 'Essex', 'Clacton', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 4543),
('Kyung Torphy', 'CO15', 'Tendring, unparished area', 'Essex', 'Clacton', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 1719),
('Kyung Torphy', 'CO15', 'Tendring, unparished area', 'Essex', 'Clacton', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 4462),
('Kyung Torphy', 'CO15', 'Tendring, unparished area', 'Essex', 'Clacton', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 3279),
('Edmond Beer', 'EN3', 'Enfield, unparished area', 'None', 'Enfield North', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 2603),
('Edmond Beer', 'EN3', 'Enfield, unparished area', 'None', 'Enfield North', 'Farming Equipment and Technology Fund', 'Horticulture', '', '22/23', 4827),
('Sanford Conroy', 'ST6', 'Brown Edge', 'Staffordshire', 'Staffordshire Moorlands', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 2490),
('Sanford Conroy', 'ST6', 'Brown Edge', 'Staffordshire', 'Staffordshire Moorlands', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 2907),
('Sanford Conroy', 'ST6', 'Brown Edge', 'Staffordshire', 'Staffordshire Moorlands', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 1480),
('Loma Little', 'CR0', 'Sutton, unparished area', 'None', 'Carshalton and Wallington', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 2893),
('Loma Little', 'CR0', 'Sutton, unparished area', 'None', 'Carshalton and Wallington', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 2007),
('Loma Little', 'CR0', 'Sutton, unparished area', 'None', 'Carshalton and Wallington', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 2252),
('Loma Little', 'CR0', 'Sutton, unparished area', 'None', 'Carshalton and Wallington', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Loma Little', 'CR0', 'Sutton, unparished area', 'None', 'Carshalton and Wallington', 'Farming Equipment and Technology Fund', 'Resource Management', '', '23/24', 4652),
('Loma Little', 'CR0', 'Sutton, unparished area', 'None', 'Carshalton and Wallington', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '23/24', 4072),
('Carroll Hilll', 'BL4', 'Bolton, unparished area', 'None', 'Bolton South East', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 3811),
('Carroll Hilll', 'BL4', 'Bolton, unparished area', 'None', 'Bolton South East', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2817),
('Carroll Hilll', 'BL4', 'Bolton, unparished area', 'None', 'Bolton South East', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '23/24', 1281),
('Carroll Hilll', 'BL4', 'Bolton, unparished area', 'None', 'Bolton South East', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '24/25', 4620),
('Laurene Turner', 'DT11', 'Iwerne Courtney or Shroton', 'None', 'North Dorset', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 3920),
('Laurene Turner', 'DT11', 'Iwerne Courtney or Shroton', 'None', 'North Dorset', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 4324),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 2268),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 4829),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 1442),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2366),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 3430),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '23/24', 3217),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Farming Equipment and Technology Fund', 'Horticulture', '', '24/25', 4545),
('Charline Tromp', 'EH14', 'None', 'None', 'Edinburgh South West', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '24/25', 3653),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 2830),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 1611),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 3922),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 1374),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 3374),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 1940),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 2274),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2682),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 2784),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 1470),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 1960),
('Arden Wintheiser', 'L11', 'Liverpool, unparished area', 'None', 'Liverpool, West Derby', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 3090),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 4936),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 2156),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 4975),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 4439),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 4580),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 4467),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 2386),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 3578),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 4385),
('Kris Wunsch', 'BB3', 'Darwen', 'None', 'Rossendale and Darwen', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 2397),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 4122),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 2711),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 1627),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 2526),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 1906),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 2789),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 2773),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 4271),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Farming Equipment and Technology Fund', 'Horticulture', '', '23/24', 1671),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 2728),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '23/24', 3125),
('Kermit Osinski', 'B10', 'Birmingham, unparished area', 'None', 'Birmingham, Hodge Hill', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '23/24', 4795),
('Tod Schaden', 'SA32', 'Abergwili', 'None', 'Carmarthen East and Dinefwr', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 2462),
('Tod Schaden', 'SA32', 'Abergwili', 'None', 'Carmarthen East and Dinefwr', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 2459),
('Tod Schaden', 'SA32', 'Abergwili', 'None', 'Carmarthen East and Dinefwr', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 3549),
('Tod Schaden', 'SA32', 'Abergwili', 'None', 'Carmarthen East and Dinefwr', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 2596),
('Tod Schaden', 'SA32', 'Abergwili', 'None', 'Carmarthen East and Dinefwr', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 1808),
('Tod Schaden', 'SA32', 'Abergwili', 'None', 'Carmarthen East and Dinefwr', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 2173),
('Meridith Corwin', 'DN1', 'Doncaster, unparished area', 'None', 'Doncaster Central', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 4862),
('Meridith Corwin', 'DN1', 'Doncaster, unparished area', 'None', 'Doncaster Central', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 2104),
('Meridith Corwin', 'DN1', 'Doncaster, unparished area', 'None', 'Doncaster Central', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '23/24', 3236),
('Efrain Stracke', 'E13', 'Newham, unparished area', 'None', 'East Ham', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 4602),
('Efrain Stracke', 'E13', 'Newham, unparished area', 'None', 'East Ham', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 3988),
('Vickie Stamm', 'AL7', 'Welwyn Hatfield, unparished area', 'Hertfordshire', 'Welwyn Hatfield', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 3040),
('Vickie Stamm', 'AL7', 'Welwyn Hatfield, unparished area', 'Hertfordshire', 'Welwyn Hatfield', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 3374),
('Vickie Stamm', 'AL7', 'Welwyn Hatfield, unparished area', 'Hertfordshire', 'Welwyn Hatfield', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 3606),
('Vickie Stamm', 'AL7', 'Welwyn Hatfield, unparished area', 'Hertfordshire', 'Welwyn Hatfield', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 3723),
('Vickie Stamm', 'AL7', 'Welwyn Hatfield, unparished area', 'Hertfordshire', 'Welwyn Hatfield', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 3968),
('Vickie Stamm', 'AL7', 'Welwyn Hatfield, unparished area', 'Hertfordshire', 'Welwyn Hatfield', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 3525),
('Eli Blanda', 'HA7', 'Harrow, unparished area', 'None', 'Harrow East', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 3591),
('Eli Blanda', 'HA7', 'Harrow, unparished area', 'None', 'Harrow East', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 3340),
('Eli Blanda', 'HA7', 'Harrow, unparished area', 'None', 'Harrow East', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 3974),
('Eli Blanda', 'HA7', 'Harrow, unparished area', 'None', 'Harrow East', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 2276),
('Eli Blanda', 'HA7', 'Harrow, unparished area', 'None', 'Harrow East', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 3161),
('Eli Blanda', 'HA7', 'Harrow, unparished area', 'None', 'Harrow East', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 4487),
('Lino Kub', 'DT7', 'Uplyme', 'Devon', 'Tiverton and Honiton', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 1791),
('Lino Kub', 'DT7', 'Uplyme', 'Devon', 'Tiverton and Honiton', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 3705),
('Lino Kub', 'DT7', 'Uplyme', 'Devon', 'Tiverton and Honiton', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 4194),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 3364),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 1851),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 1411),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 3233),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 1427),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 1516),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 2444),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 4628),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '22/23', 2238),
('Letha Hodkiewicz', 'CF11', 'Grangetown', 'None', 'Cardiff South and Penarth', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 4079),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 3323),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 1681),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 3290),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 4322),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 4256),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 2154),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 3448),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 1333),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 4648),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 1476),
('Stacey Brakus', 'CA8', 'Coanwood', 'None', 'Hexham', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Angila Beier', 'M9', 'Manchester, unparished area', 'None', 'Blackley and Broughton', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 1668),
('Angila Beier', 'M9', 'Manchester, unparished area', 'None', 'Blackley and Broughton', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 1381),
('Angila Beier', 'M9', 'Manchester, unparished area', 'None', 'Blackley and Broughton', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 4820),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 3141),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 2242),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 3725),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 3588),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 3184),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 4299),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 2861),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '23/24', 1613),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Farming Equipment and Technology Fund', 'Horticulture', '', '24/25', 2598),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '24/25', 4148),
('Maira Schoen', 'DG11', 'None', 'None', 'Dumfriesshire, Clydesdale and Tweeddale', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '24/25', 3288),
('Van Erdman', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 3581),
('Van Erdman', 'SK1', 'Stockport, unparished area', 'None', 'Stockport', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 3829),
('Gregorio Lang', 'NG2', 'Rushcliffe, unparished area', 'Nottinghamshire', 'Rushcliffe', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '21/22', 3991),
('Gregorio Lang', 'NG2', 'Rushcliffe, unparished area', 'Nottinghamshire', 'Rushcliffe', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 2714),
('Gregorio Lang', 'NG2', 'Rushcliffe, unparished area', 'Nottinghamshire', 'Rushcliffe', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '23/24', 4083),
('Gregorio Lang', 'NG2', 'Rushcliffe, unparished area', 'Nottinghamshire', 'Rushcliffe', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '24/25', 3574),
('Janis Kuphal', 'CM7', 'Braintree, unparished area', 'Essex', 'Braintree', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 2651),
('Janis Kuphal', 'CM7', 'Braintree, unparished area', 'Essex', 'Braintree', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 3780),
('Janis Kuphal', 'CM7', 'Braintree, unparished area', 'Essex', 'Braintree', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 3149),
('Janis Kuphal', 'CM7', 'Braintree, unparished area', 'Essex', 'Braintree', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 3816),
('Janis Kuphal', 'CM7', 'Braintree, unparished area', 'Essex', 'Braintree', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 1446),
('Janis Kuphal', 'CM7', 'Braintree, unparished area', 'Essex', 'Braintree', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 1933),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '21/22', 1905),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 2201),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 2984),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 1895),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 3370),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 3262),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 3382),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '22/23', 2769),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 1290),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 4456),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'Resource Management', '', '23/24', 3875),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 3453),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 4976),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'General', '', '23/24', 1788),
('Taylor Wolf', 'TQ9', 'Dartington', 'Devon', 'Totnes', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '23/24', 4271),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 1631),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 4856),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 3465),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '21/22', 2547),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 2335),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 3847),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 3138),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 3910),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 4863),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 4553),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 4771),
('Donovan Kozey', 'EH3', 'None', 'None', 'Edinburgh North and Leith', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '22/23', 4867),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 3687),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 1906),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '21/22', 1951),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 4304),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 4923),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 1668),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 1845),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '23/24', 1250),
('Michel Johns', 'W7', 'Ealing, unparished area', 'None', 'Ealing North', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '23/24', 1968),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 3499),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 5000),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 1792),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Horticulture', '', '21/22', 4311),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 4652),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 3288),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 1839),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '22/23', 1250),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '22/23', 4188),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '22/23', 3308),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2813),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 4239),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 3207),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '23/24', 1995),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', '', '23/24', 2908),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 3656),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Forestry', '', '23/24', 4310),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '23/24', 2868),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '24/25', 4731),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Resource Management', '', '24/25', 4280),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'General', '', '24/25', 4867),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '24/25', 4138),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Farming Equipment and Technology Fund', 'Precision and Analysis', '', '24/25', 1680),
('Queen Aufderhar', 'LE17', 'Ashby Magna', 'Leicestershire', 'South Leicestershire', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '24/25', 2150),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 3811),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 3230),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 2930),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 1298),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '22/23', 2159),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 1368),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 3626),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Forestry', '', '22/23', 3898),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '23/24', 4993),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '23/24', 4992),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 3564),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Horticulture', '', '23/24', 2517),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '24/25', 2381),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Forestry', '', '24/25', 3182),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'Horticulture', '', '24/25', 2072),
('Teodora Hermann', 'DT2', 'Melbury Sampford', 'None', 'West Dorset', 'Farming Equipment and Technology Fund', 'General', '', '24/25', 3131),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '21/22', 1250),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 4976),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '21/22', 4640),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Farming Equipment and Technology Fund', 'General', '', '21/22', 2988),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '21/22', 4838),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Farming Equipment and Technology Fund', 'Forestry', '', '21/22', 4006),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 2614),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 1970),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Farming Equipment and Technology Fund', 'General', '', '22/23', 3341),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 2690),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', '', '22/23', 1501),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '22/23', 3936),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Pilot Participation Payment', '', '23/24', 1250),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Hedgerow', '', '23/24', 1760),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', '', '23/24', 1352),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Farming Equipment and Technology Fund', 'Horticulture', '', '23/24', 4961),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Sustainable Farming Incentive Pilot', 'Improved Grassland soils', '', '23/24', 1960),
('Arnoldo Shanahan', 'M28', 'Salford, unparished area', 'None', 'Worsley and Eccles South', 'Farming Equipment and Technology Fund', 'Resource Management', '', '23/24', 4041),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Farming Equipment and Technology Fund', 'Resource Management', '', '21/22', 2670),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '21/22', 1703),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', '', '21/22', 4146),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '21/22', 4232),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', '', '21/22', 2729),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 2006),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 2170),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 3239),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Sustainable Farming Incentive Pilot', 'On farm woodland', '', '22/23', 3640),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Farming Equipment and Technology Fund', 'Livestock Handling and weighing equipment', '', '22/23', 4904),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Farming Equipment and Technology Fund', 'Resource Management', '', '22/23', 3606),
('Jessie Brown', 'LE13', 'Melton, unparished area', 'Leicestershire', 'Rutland and Melton', 'Farming Equipment and Technology Fund', 'Horticulture', '', '22/23', 4085),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '21/22', 3421),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Sustainable Farming Incentive Pilot', 'Other Livestock equipment', '', '21/22', 3422),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '22/23', 3421),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Sustainable Farming Incentive Pilot', 'Other Livestock equipment', '', '22/23', 3422),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '23/24', 3421),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Sustainable Farming Incentive Pilot', 'Other Livestock equipment', '', '23/24', 3422),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '24/25', 3421),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Sustainable Farming Incentive Pilot', 'Other Livestock equipment', '', '24/25', 3422),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Farming Equipment and Technology Fund', 'Other Livestock equipment', '', '25/26', 3421),
('Vel Muthu', 'TR16', 'Illogan', 'None', 'Camborne and Redruth', 'Sustainable Farming Incentive Pilot', 'Other Livestock equipment', '', '25/26', 3422);
