INSERT INTO public."payment_activity_data" (payee_name, part_postcode, town, county, parliamentary_constituency, scheme, activity_detail, amount) VALUES ('Trinidad Nicolas', 'EH4', None, None, 'Edinburgh West', 'Farming Equipment and Technology Fund', 'Resource Management', 4096),
('Trinidad Nicolas', 'EH4', None, None, 'Edinburgh West', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', 3018),
('Trinidad Nicolas', 'EH4', None, None, 'Edinburgh West', 'Sustainable Farming Incentive Pilot', 'On farm woodland', 3775),
('Trinidad Nicolas', 'EH4', None, None, 'Edinburgh West', 'Farming Equipment and Technology Fund', 'Horticulture', 3303),
('Trinidad Nicolas', 'EH4', None, None, 'Edinburgh West', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', 3461),
('Trinidad Nicolas', 'EH4', None, None, 'Edinburgh West', 'Farming Equipment and Technology Fund', 'Resource Management', 3350),
('Margarite Will', 'SA1', 'Bonymaen', None, 'Swansea East', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', 1346),
('Margarite Will', 'SA1', 'Bonymaen', None, 'Swansea East', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Land', 3083),
('Margarite Will', 'SA1', 'Bonymaen', None, 'Swansea East', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', 1707),
('Kendall Macejkovic', 'BS48', 'Backwell', None, 'North Somerset', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', 1715),
('Kendall Macejkovic', 'BS48', 'Backwell', None, 'North Somerset', 'Sustainable Farming Incentive Pilot', 'Arable and Horticultural Soils', 2147),
('Sharilyn Sauer', 'SR8', 'Peterlee', None, 'Easington', 'Farming Equipment and Technology Fund', 'Precision and Analysis', 1633),
('Sharilyn Sauer', 'SR8', 'Peterlee', None, 'Easington', 'Sustainable Farming Incentive Pilot', 'Low and no input Grassland', 4442),
('Sharilyn Sauer', 'SR8', 'Peterlee', None, 'Easington', 'Farming Equipment and Technology Fund', 'Precision and Analysis', 2041),
('Van Anderson', 'HA5', 'Harrow, unparished area', None, 'Ruislip, Northwood and Pinner', 'Sustainable Farming Incentive Pilot', 'Waterbody Buffering', 4531),
('Van Anderson', 'HA5', 'Harrow, unparished area', None, 'Ruislip, Northwood and Pinner', 'Sustainable Farming Incentive Pilot', 'Improved Grassland', 4266),
